// <auto-generated />
using IdentityHost.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace IdentityHost.Migrations.IdentityServer.CoreApiMappingDb
{
    [DbContext(typeof(CoreApiMappingDbContext))]
    partial class CoreApiMappingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentityHost.Contexts.ApiMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientId");

                    b.Property<string>("CoreApiEndPoint");

                    b.Property<string>("CoreToken");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("ApiMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
